name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.hash.outputs.hash }}
    steps:
      - uses: actions/checkout@v4
      
      - id: hash
        run: |
          hash=$(echo -n "${{ github.repository }}-${{ github.run_id }}" | sha256sum | cut -c1-8)
          echo "hash=$hash" >> $GITHUB_OUTPUT
      
      - uses: Platane/snk@v3
        with:
          github_user_name: Ayan-Flash
          outputs: |
            dist/snake-light.svg
            dist/snake-dark.svg
            dist/snake.gif
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: Download snake artifacts
        uses: actions/download-artifact@v4
        with:
          name: snake-artifacts
          path: dist
      - name: Commit and Push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          github-actions[bot]
          
          git add -A
          git commit -m "Update snake animation - ${{ needs.build.outputs.hash }}" || echo "No changes to commit"
          
          git push origin master --force
